# Community Announcements Edge Function Configuration

[function]
name = "community-announcements"
verify_jwt = false  # We handle JWT verification manually for better error handling

[function.permissions]
read_access = ["authenticated"]
write_access = ["admin"]

[function.rate_limiting]
enabled = true
max_requests_per_minute = 60
max_requests_per_hour = 1000

[function.caching]
enabled = false  # Disable caching for real-time announcement updates

[function.env]
SUPABASE_URL = "required"
SUPABASE_SERVICE_ROLE_KEY = "required"