// ABOUTME: Tests for AdminUserManagement ensuring StandardLayout integration and proper user management interface behavior

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MockAllProviders } from '@/test-utils/mock-providers';
import AdminUserManagement from './AdminUserManagement';

// Mock components that might not be available during testing
vi.mock('@/components/admin/UserManagement/UserListTable', () => ({
  UserListTable: () => <div data-testid="user-list-table">User List Table Component</div>
}));

describe('AdminUserManagement', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('layout structure', () => {
    it('should render with ErrorBoundary wrapper', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have ErrorBoundary structure
      const errorBoundary = document.querySelector('[data-error-boundary]');
      expect(errorBoundary).toBeInTheDocument();
    });

    it('should render with StandardLayout wide type', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have main element with wide layout characteristics
      const main = screen.getByRole('main');
      expect(main).toBeInTheDocument();
      expect(main).toHaveClass('max-w-6xl'); // StandardLayout 'wide' type
      expect(main).toHaveClass('mx-auto');   // Centering
    });

    it('should have proper spacing with contentClassName', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      expect(main).toHaveClass('space-y-6'); // contentClassName applied
    });

    it('should center content within available space', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Check for centering wrapper (generated by StandardLayout)
      const centeringWrapper = document.querySelector('.flex.justify-center');
      expect(centeringWrapper).toBeInTheDocument();
    });
  });

  describe('content structure', () => {
    it('should display the page header with proper typography', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const heading = screen.getByRole('heading', { level: 2 });
      expect(heading).toBeInTheDocument();
      expect(heading).toHaveTextContent('Gestão de Usuários');
      expect(heading).toHaveClass('text-3xl', 'font-bold', 'font-serif');
    });

    it('should display page description', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const description = screen.getByText(/Gerencie usuários, papéis e permissões/);
      expect(description).toBeInTheDocument();
    });

    it('should render UserListTable component', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const userTable = screen.getByTestId('user-list-table');
      expect(userTable).toBeInTheDocument();
    });
  });

  describe('responsive behavior', () => {
    it('should maintain proper spacing on all screen sizes', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      expect(main).toHaveClass('space-y-6'); // Consistent spacing
    });

    it('should adapt layout for mobile devices', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // StandardLayout should handle mobile adaptation
      const main = screen.getByRole('main');
      expect(main).toHaveClass('w-full'); // Full width within constraints
    });
  });

  describe('accessibility', () => {
    it('should have proper semantic structure', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have main landmark
      const main = screen.getByRole('main');
      expect(main).toBeInTheDocument();

      // Should have proper heading hierarchy
      const mainHeading = screen.getByRole('heading', { level: 2 });
      expect(mainHeading).toBeInTheDocument();
    });

    it('should have accessible header structure', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const header = document.querySelector('.mb-6.space-y-2');
      expect(header).toBeInTheDocument();

      const heading = screen.getByRole('heading');
      const description = screen.getByText(/Gerencie usuários/);
      
      expect(heading).toBeInTheDocument();
      expect(description).toBeInTheDocument();
    });
  });

  describe('error boundary integration', () => {
    it('should be wrapped in ErrorBoundary with correct props', () => {
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
      
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have error boundary attributes
      const errorBoundary = document.querySelector('[data-error-boundary]');
      expect(errorBoundary).toBeInTheDocument();

      consoleSpy.mockRestore();
    });

    it('should have proper error boundary configuration', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Component should render without throwing errors
      const heading = screen.getByText('Gestão de Usuários');
      expect(heading).toBeInTheDocument();
    });
  });

  describe('layout integration compliance', () => {
    it('should follow StandardLayout architecture pattern', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should have StandardLayout 'wide' characteristics
      expect(main).toHaveClass('max-w-6xl'); // Wide type max-width
      expect(main).toHaveClass('mx-auto');   // Centering
      expect(main).toHaveClass('w-full');    // Full width within constraints
    });

    it('should not have custom layout implementations', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should NOT have old custom container classes
      const customContainer = document.querySelector('.container.mx-auto');
      expect(customContainer).not.toBeInTheDocument();

      // Should NOT have old space-y-6 div wrapper
      const customSpacing = document.querySelector('div.space-y-6 > div.mb-6');
      expect(customSpacing).not.toBeInTheDocument();
    });

    it('should maintain content width constraints', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should have proper width constraints (not full screen width)
      expect(main).toHaveClass('max-w-6xl');
      
      // Should not touch screen edges
      expect(main).not.toHaveClass('w-screen');
      expect(main).not.toHaveClass('min-w-full');
    });

    it('should not violate layout system architecture', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should be wrapped in ErrorBoundary + StandardLayout pattern
      const errorBoundary = document.querySelector('[data-error-boundary]');
      const main = screen.getByRole('main');
      
      expect(errorBoundary).toBeInTheDocument();
      expect(main).toBeInTheDocument();
      expect(main).toHaveClass('max-w-6xl'); // Proper constraints
    });
  });

  describe('user management functionality', () => {
    it('should render user management interface', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have user table component
      const userTable = screen.getByTestId('user-list-table');
      expect(userTable).toBeInTheDocument();
    });

    it('should provide proper context for user management', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Should have descriptive content about user management
      const description = screen.getByText(/Gerencie usuários, papéis e permissões/);
      expect(description).toBeInTheDocument();
    });
  });

  describe('administrative role compliance', () => {
    it('should be accessible only to admin users', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      // Component should render for admin context
      const heading = screen.getByText('Gestão de Usuários');
      expect(heading).toBeInTheDocument();
    });

    it('should maintain admin-specific styling', () => {
      render(
        <MockAllProviders>
          <AdminUserManagement />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should use 'wide' layout appropriate for admin interfaces
      expect(main).toHaveClass('max-w-6xl');
    });
  });
});