// ABOUTME: Tests for AdminAccessControl ensuring StandardLayout integration and proper access control interface behavior

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MockAllProviders } from '@/test-utils/mock-providers';
import AdminAccessControl from './AdminAccessControl';

// Mock admin components that might not exist yet
vi.mock('@/components/admin/PageAccessControlManager', () => ({
  PageAccessControlManager: () => <div data-testid="page-access-control-manager">Page Access Control Manager Component</div>
}));

describe('AdminAccessControl', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('layout structure', () => {
    it('should render with ErrorBoundary wrapper', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should render children without errors (indicating ErrorBoundary is working)
      const main = screen.getByRole('main');
      expect(main).toBeInTheDocument();
    });

    it('should render with StandardLayout wide type', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should have main element with wide layout characteristics
      const main = screen.getByRole('main');
      expect(main).toBeInTheDocument();
      expect(main).toHaveClass('max-w-6xl'); // StandardLayout 'wide' type
      expect(main).toHaveClass('mx-auto');   // Centering
    });

    it('should have proper spacing with contentClassName', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      expect(main).toHaveClass('space-y-6'); // contentClassName applied
    });

    it('should center content within available space', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Check for centering wrapper (generated by StandardLayout)
      const centeringWrapper = document.querySelector('.flex.justify-center');
      expect(centeringWrapper).toBeInTheDocument();
    });
  });

  describe('content structure', () => {
    it('should display the page header with proper typography', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const heading = screen.getByRole('heading', { level: 2 });
      expect(heading).toBeInTheDocument();
      expect(heading).toHaveTextContent('Controle de Acesso');
      expect(heading).toHaveClass('text-3xl', 'font-bold', 'font-serif');
    });

    it('should display page description', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const description = screen.getByText(/Configure regras de acesso para páginas/);
      expect(description).toBeInTheDocument();
    });

    it('should render PageAccessControlManager component', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const accessControlManager = screen.getByTestId('page-access-control-manager');
      expect(accessControlManager).toBeInTheDocument();
    });
  });

  describe('responsive behavior', () => {
    it('should maintain proper spacing on all screen sizes', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      expect(main).toHaveClass('space-y-6'); // Consistent spacing
    });

    it('should adapt layout for mobile devices', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // StandardLayout should handle mobile adaptation
      const main = screen.getByRole('main');
      expect(main).toHaveClass('w-full'); // Full width within constraints
    });
  });

  describe('accessibility', () => {
    it('should have proper semantic structure', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should have main landmark
      const main = screen.getByRole('main');
      expect(main).toBeInTheDocument();

      // Should have proper heading hierarchy
      const mainHeading = screen.getByRole('heading', { level: 2 });
      expect(mainHeading).toBeInTheDocument();
    });

    it('should have accessible header structure', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const header = document.querySelector('.mb-6.space-y-2');
      expect(header).toBeInTheDocument();

      const heading = screen.getByRole('heading');
      const description = screen.getByText(/Configure regras de acesso/);
      
      expect(heading).toBeInTheDocument();
      expect(description).toBeInTheDocument();
    });
  });

  describe('error boundary integration', () => {
    it('should be wrapped in ErrorBoundary with correct props', () => {
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
      
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should render without throwing errors (indicating ErrorBoundary is working)
      const heading = screen.getByText('Controle de Acesso');
      expect(heading).toBeInTheDocument();

      consoleSpy.mockRestore();
    });

    it('should have proper error boundary configuration', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Component should render without throwing errors
      const heading = screen.getByText('Controle de Acesso');
      expect(heading).toBeInTheDocument();
    });
  });

  describe('layout integration compliance', () => {
    it('should follow StandardLayout architecture pattern', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should have StandardLayout 'wide' characteristics
      expect(main).toHaveClass('max-w-6xl'); // Wide type max-width
      expect(main).toHaveClass('mx-auto');   // Centering
      expect(main).toHaveClass('w-full');    // Full width within constraints
    });

    it('should not have custom layout implementations', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should NOT have old custom container classes
      const customContainer = document.querySelector('.container.mx-auto');
      expect(customContainer).not.toBeInTheDocument();

      // Should NOT have old space-y-6 div wrapper
      const customSpacing = document.querySelector('div.space-y-6 > div.mb-6');
      expect(customSpacing).not.toBeInTheDocument();
    });

    it('should maintain content width constraints', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should have proper width constraints (not full screen width)
      expect(main).toHaveClass('max-w-6xl');
      
      // Should not touch screen edges
      expect(main).not.toHaveClass('w-screen');
      expect(main).not.toHaveClass('min-w-full');
    });

    it('should not violate layout system architecture', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should be wrapped in ErrorBoundary + StandardLayout pattern
      const main = screen.getByRole('main');
      
      expect(main).toBeInTheDocument();
      expect(main).toHaveClass('max-w-6xl'); // Proper constraints
    });
  });

  describe('administrative role compliance', () => {
    it('should be accessible only to admin users', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Component should render for admin context
      const heading = screen.getByText('Controle de Acesso');
      expect(heading).toBeInTheDocument();
    });

    it('should maintain admin-specific styling', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      const main = screen.getByRole('main');
      
      // Should use 'wide' layout appropriate for admin interfaces
      expect(main).toHaveClass('max-w-6xl');
    });
  });

  describe('access control functionality', () => {
    it('should render access control management interface', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should have access control manager component
      const accessManager = screen.getByTestId('page-access-control-manager');
      expect(accessManager).toBeInTheDocument();
    });

    it('should provide proper context for access control management', () => {
      render(
        <MockAllProviders>
          <AdminAccessControl />
        </MockAllProviders>
      );

      // Should have descriptive content about access control
      const description = screen.getByText(/Configure regras de acesso para páginas e recursos/);
      expect(description).toBeInTheDocument();
    });
  });
});